const appTheme = createTheme({
  palette: {
    themePrimary: "#128c7e",
    themeLighterAlt: "#f2faf9",
    themeLighter: "#ccede9",
    themeLight: "#a3ddd6",
    themeTertiary: "#59baaf",
    themeSecondary: "#249a8c",
    themeDarkAlt: "#107e71",
    themeDark: "#0e6b60",
    themeDarker: "#0a4f47",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
});
